settings: throw custom exceptions when accessing undefined section/attribute
Watch out, glib seems to screw the custom exception, maybe because they use multiple
inheritance, and report a bad one:

     TypeError: __init__() missing 1 required positional argument: 'attr'

So better to catch this exception earlier and handle it to make the prog exit more
clean. This will be done soon.